=== NCAR/MechanismToCode/schemas/chemical_system.json
{
  "$schema" : "http://json-schema.org/schema#",

  "$id" : "http://github.com/NCAR/MechanismToCode/schemas/chemical_system.json",
  "type" : "object",
  "description" : "A complete aerosol system: gases, particles, and processes that affect them.",
  "properties" : {
    "chemical species" : {
      "type" : "object",
      "patternProperties" : {
        "" : { "$ref" : "http://github.com/NCAR/MechanismToCode/schemas/chemical_species/species.json" }
      },
      "additionalProperties" : false
    },
    "phases" : {
      "type" : "object",
      "patternProperties" : {
        "" : { "$ref" : "http://github.com/NCAR/MechanismToCode/schemas/aerosol/phase.json" }
      },
      "additionalProperties" : false
    },
    "aerosol representation" : {
        "$ref" : "http://github.com/NCAR/MechanismToCode/schemas/aerosol/representation.json"
    },
    "mechanisms" : {
      "type" : "object",
      "patternProperties" : {
        "" : { "$ref" : "http://github.com/NCAR/MechanismToCode/schemas/mechanism.json" }
      },
      "additionalProperties" : false
    }
  },
  "required" : [ "chemical species", "phases", "aerosol representation", "mechanisms" ]
}

=== NCAR/MechanismToCode/test/schemas/test_scenarios/test_troe.json
{
  "chemical species" : {
    "O" : {
      "long name" : "oxygen radical O(3P)",
      "standard properties" : {
        "chemical formula" : "O"
      }
    },
    "NO2" : {
      "long name" : "nitrogen dioxide",
      "standard properties" : {
        "chemical formula" : "NO2"
      }
    },
    "NO3" : {
      "long name" : "nitrate radical",
      "standard propertes" : {
        "chemical formula" : "NO3"
      }
    }
  },
  "phases" : {
    "gas" : { "species" : [ "O", "NO2", "NO3" ] }
  },
  "aerosol representation" : {
    "gas phase" : "gas",
    "components" : { }
  },
  "mechanisms" : {
    "simple arrhenius" : {
      "processes" : {
        "RXN_O_NO2__NO3" : {
          "TYPE" : "PROCESS_ITH_ORDER",
          "phase" : "gas",
          "reactants" : {
            "O" : { },
            "NO2" : { }
          },
          "products" : {
            "NO3" : { }
          },
          "rate constant" : {
            "TYPE" : "RATE_CONST_TROE",
            "k0_A" : 2.5E-31,
            "k0_B" : -1.8,
            "k0_C" : -0.0E+00,
            "kinf_A" : 2.2E-11,
            "kinf_B" : -0.7,
            "kinf_C" : -0.0E+00,
            "Fc" : 0.6,
            "N" : 1.0
          }
        }
      }
    }
  }
}

=== NCAR/MechanismToCode/test/schemas/test_scenarios/test_CMAQ_OH_HNO3.json
{
  "chemical species" : {
    "OH" : {
      "long name" : "hydroxyl radical",
      "standard properties" : {
        "chemical formula" : "OH"
      }
    },
    "HNO3" : {
      "long name" : "nitric acid",
      "standard properties" : {
        "chemical formula" : "HNO3"
      }
    },
    "NO3" : {
      "long name" : "nitrate radical",
      "standard propertes" : {
        "chemical formula" : "NO3"
      }
    }
  },
  "phases" : {
    "gas" : { "species" : [ "OH", "HNO3", "NO3" ] }
  },
  "aerosol representation" : {
    "gas phase" : "gas",
    "components" : { }
  },
  "mechanisms" : {
    "simple arrhenius" : {
      "processes" : {
        "RXN_OH_HNO3__NO3" : {
          "TYPE" : "PROCESS_ITH_ORDER",
          "phase" : "gas",
          "reactants" : {
            "OH" : { },
            "HNO3" : { }
          },
          "products" : {
            "NO3" : { }
          },
          "rate constant" : {
            "TYPE" : "RATE_CONST_CMAQ_OH_HNO3",
            "k0_A" : 2.4E-14,
            "k0_C" : 460.0,
            "k2_A" : 2.7E-17,
            "k2_C" : 2199.0,
            "k3_A" : 6.5E-34,
            "k3_C" : 1335.0
          }
        }
      }
    }
  }
}

=== NCAR/MechanismToCode/test/schemas/test_scenarios/test_arrhenius.json
{
  "chemical species" : {
    "O3" : {
      "long name" : "ozone",
      "standard properties" : {
        "chemical formula" : "O3"
      }
    },
    "NO2" : {
      "long name" : "nitrogen dioxide",
      "standard properties" : {
        "chemical formula" : "NO2"
      }
    },
    "NO" : {
      "long name" : "nitrogen oxide",
      "standard propertes" : {
        "chemical formula" : "NO"
      }
    },
    "O2" : {
      "long name" : "molecular oxygen",
      "standard properties" : {
        "chemical formula" : "O2"
      }
    }
  },
  "phases" : {
    "gas" : { "species" : [ "O3", "NO2", "NO" ] }
  },
  "aerosol representation" : {
    "gas phase" : "gas",
    "components" : { }
  },
  "mechanisms" : {
    "simple arrhenius" : {
      "processes" : {
        "RXN_O3_NO__NO2" : {
          "TYPE" : "PROCESS_ITH_ORDER",
          "phase" : "gas",
          "reactants" : {
            "O3" : { },
            "NO" : { }
          },
          "products" : {
            "NO2" : { }
          },
          "rate constant" : {
            "TYPE" : "RATE_CONST_ARRHENIUS",
            "A" : 3.0E-12,
            "C" : -1500.0
          }
        },
        "RXN_2NO_O2__NO2" : {
          "TYPE" : "PROCESS_ITH_ORDER",
          "phase" : "gas",
          "reactants" : {
            "NO" : { "number" : 2 }
          },
          "products" : {
            "NO2" : { "yield" : 2.0 }
          },
          "rate constant" : {
            "TYPE" : "RATE_CONST_ARRHENIUS",
            "A" : 3.3E-39,
            "C" : 530.0
          }
        }
      }
    }
  }
}

=== NCAR/MechanismToCode/test/schemas/test_scenarios/test_constant.json
{
  "chemical species" : {
    "NO2" : {
      "long name" : "nitrogen dioxide",
      "standard properties" : {
        "chemical formula" : "NO2"
      }
    },
    "NO" : {
      "long name" : "nitrogen oxide",
      "standard propertes" : {
        "chemical formula" : "NO"
      }
    },
    "O" : {
      "long name" : "oxygen radical - O(3P)",
      "standard properties" : {
        "chemical formula" : "O"
      }
    }
  },
  "phases" : {
    "gas" : { "species" : [ "NO2", "NO", "O" ] }
  },
  "aerosol representation" : {
    "gas phase" : "gas",
    "components" : { }
  },
  "mechanisms" : {
    "simple arrhenius" : {
      "processes" : {
        "RXN_NO2__NO_O" : {
          "TYPE" : "PROCESS_FIRST_ORDER",
          "phase" : "gas",
          "reactant" : "NO2",
          "products" : {
            "NO" : { },
            "O" : { }
          },
          "rate constant" : {
            "TYPE" : "RATE_CONST_CONSTANT"
          }
        }
      }
    }
  }
}

=== NCAR/MechanismToCode/test/schemas/test_scenarios/test_CMAQ_H2O2.json
{
  "chemical species" : {
    "HO2" : {
      "long name" : "hydroperoxy radical",
      "standard properties" : {
        "chemical formula" : "HO2"
      }
    },
    "H2O2" : {
      "long name" : "hydrogen peroxide",
      "standard properties" : {
        "chemical formula" : "H2O2"
      }
    }
  },
  "phases" : {
    "gas" : { "species" : [ "HO2", "H2O2"] }
  },
  "aerosol representation" : {
    "gas phase" : "gas",
    "components" : { }
  },
  "mechanisms" : {
    "simple arrhenius" : {
      "processes" : {
        "RXN_O3_NO__NO2" : {
          "TYPE" : "PROCESS_ITH_ORDER",
          "phase" : "gas",
          "reactants" : {
            "HO2" : { "number" : 2 }
          },
          "products" : {
            "H2O2" : { }
          },
          "rate constant" : {
            "TYPE" : "RATE_CONST_CMAQ_H2O2",
            "k1_A" : 2.3E-13,
            "k1_C" : 6.0E+02,
            "k2_A" : 1.7E-33,
            "k2_C" : 1.0E+03
          }
        }
      }
    }
  }
}
